### ISSUE TITLE
「Gridea」主题文件中这在哪里

### ISSUE THREAD

**Issue by Qign** [GalaxySuze/gridea-theme-space#1]
在哪里？

**Comment by GalaxySuze** [comment]
1. 打开 Gridea ，点击左边 「系统」菜单
2. 点击上方「源文件夹」选项页，选项中会显示当前软件文件保存所在路径
3. 进入此路径，路径目录下有一个「themes」目录
4. 这个目录就是存放主题文件的地方，clone 此主题后，将「space」目录放入其中，重启 Gridea，使用主题

**Comment by Qign** [comment]
多谢大佬，我丢到安装目录里面的那个去了。难怪没反应
