### ISSUE TITLE
资源文件404

### ISSUE THREAD

**Issue by iTsubasa597** [GalaxySuze/gridea-theme-space#2]
media/scripts/_vendors/目录下的文件全都404

**Comment by JokerZhang98** [comment]
对啊，我也这样，解决了吗~~PS：主题挺好看，想用

**Comment by iTsubasa597** [comment]
@JokerZhang98 

解决方法 :

1. 将 **themes/space/assets/media/_vendors** 目录下的文件复制到 **themes/space/assets/media/**
2. 修改 **themes/space/templates/_blocks/** 下 **scripts.ejs** 和 **head.ejs** 中对 js 的引用  

源代码
```
<script src="<%= themeConfig.domain %>/media/scripts/_vendors/modernizr-2.6.2.min.js"></script>
```

修改后
```
<script src="<%= themeConfig.domain %>/media/scripts/modernizr-2.6.2.min.js"></script>
```

**Comment by JokerZhang98** [comment]
@iTsubasa597 
1、本地文件media文件下没得_vendors这个文件夹（也没有隐藏的）~~
2、 scripts.ejs 与head.ejs文件里面没有这连个引用

**Comment by JokerZhang98** [comment]
@iTsubasa597  
  不知道哪里搞错了，谢谢大佬帮忙

**Comment by JokerZhang98** [comment]
@iTsubasa597 
1、 themes/space/assets/media/这个目录下没有_vendors这个文件夹，_vendors文件在这个路径下面space\assets\media\scripts\_vendors，我没得搞懂你的意思
2、scripts.ejs里面没有这个js引用是要添加上嘛

ps:谢谢大佬

**Comment by iTsubasa597** [comment]
@JokerZhang98 
1. 目录的话应该是 space/assets/media/scripts/ 下的 _vendors, 我看错了
2. 下载最新的项目文件, 里面会有``` <script>``` 标签

**Comment by JokerZhang98** [comment]
@iTsubasa597 
老哥加个联系方式吧 我人晕了，没找到啊，我下载的就是最新的

**Comment by iTsubasa597** [comment]
@JokerZhang98 微信号 SneezyDwarfe

**Comment by GalaxySuze** [comment]
仓库已经更新，具体导致原因可见此条[pull request](https://github.com/GalaxySuze/gridea-theme-space/pull/6#issue-358867032)，感谢对此主题的支持。年前空闲，因为Gridea大更新，也准备大更新主题一波。提前祝贺一下新年快乐~
