### ISSUE TITLE
侧滑不能点开

### ISSUE THREAD

**Issue by fafayaa** [GalaxySuze/gridea-theme-space#3]
Rt
地址 http://0ya.cc

**Comment by GalaxySuze** [comment]
你好，查看你的网站请求，部分资源未成功加载，请确认下以下主题文件路径是否有文件存在

> space/assets/media/scripts/_vendors/

**Comment by GalaxySuze** [comment]
仓库已经更新，具体导致原因可见此条[pull request](https://github.com/GalaxySuze/gridea-theme-space/pull/6#issue-358867032)，感谢对此主题的支持。年前空闲，因为Gridea大更新，也准备大更新主题一波。提前祝贺一下新年快乐~
