### ISSUE TITLE
js加载失败

### ISSUE THREAD

**Issue by 43907800** [GalaxySuze/gridea-theme-space#5]
https://43907800.github.io/media/scripts/_vendors/main.js

路径是对的,是为什么呢?

**Comment by 43907800** [comment]
确认 media/scripts/_vendors 下存在js文件

**Comment by GalaxySuze** [comment]
你好，可以看下博客仓库中media/scripts/_vendors中的js文件是否已经推送到仓库

**Comment by zsychn** [comment]
我也遇到了同样的问题。看了下，推送到仓库了。
https://tva1.sinaimg.cn/large/006y8mN6ly1g96lb9svgkj31hb0ann0x.jpg

**Comment by GalaxySuze** [comment]
> 我也遇到了同样的问题。看了下，推送到仓库了。
> https://tva1.sinaimg.cn/large/006y8mN6ly1g96lb9svgkj31hb0ann0x.jpg

嗯你好，问下是用的coding还是github的page服务呢？我现在测试了下coding是正常的，github我晚上测试下看看

**Comment by TimeBoat** [comment]
> > 我也遇到了同样的问题。看了下，推送到仓库了。
> > https://tva1.sinaimg.cn/large/006y8mN6ly1g96lb9svgkj31hb0ann0x.jpg
> 
> 嗯你好，问下是用的coding还是github的page服务呢？我现在测试了下coding是正常的，github我晚上测试下看看

UP主您好！我在Github Pages下使用您的Space主题时遇到了同样的问题：静态本地预览可以正常显示，但是实际环境无法加载已经上传了的JS
PS：您的主题很好看，希望能在Github上使用呀，谢谢

**Comment by iTsubasa597** [comment]
Github 上的解决方法 : 

1. 将 **themes/space/assets/media/_vendors** 目录下的文件复制到 **themes/space/assets/media/**
2. 修改 **themes/space/templates/_blocks/** 下 **scripts.ejs** 和 **head.ejs** 中对 js 的引用

源代码
```
<script src="<%= themeConfig.domain %>/media/scripts/_vendors/modernizr-2.6.2.min.js"></script>
```

修改后
```
<script src="<%= themeConfig.domain %>/media/scripts/modernizr-2.6.2.min.js"></script>
```

**Comment by TimeBoat** [comment]
所以说是不识别"_"下划线路径的问题？
总之，按照你的方法，问题已经完美解决！！感谢！

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by aturX** [comment]
[JS加载报错解决](https://github.com/aturX/gridea-theme-space)
照楼上说的修复了一下。

**Comment by TimeBoat** [comment]
啊已经按照楼上的解决了！
感谢
忘记close了

Sent from ProtonMail Mobile

在 周五, 1月 3, 2020 在 12:16, Atur <notifications@github.com> 来信：

**Comment by GalaxySuze** [comment]
仓库已经更新，具体导致原因可见此条[pull request](https://github.com/GalaxySuze/gridea-theme-space/pull/6#issue-358867032)，感谢对此主题的支持。年前空闲，因为Gridea大更新，也准备大更新主题一波。提前祝贺一下新年快乐~
